<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'skytells\\wp\\skyav\\about' => '/skytells/wp/skyav/about.php',
                'skytells\\wp\\skyav\\admin' => '/skytells/wp/skyav/admin.php',
                'skytells\\wp\\skyav\\ajax' => '/skytells/wp/skyav/ajax.php',
                'skytells\\wp\\skyav\\cli' => '/skytells/wp/skyav/cli.php',
                'skytells\\wp\\skyav\\cli\\checksums' => '/skytells/wp/skyav/cli/checksums.php',
                'skytells\\wp\\skyav\\cli\\scan' => '/skytells/wp/skyav/cli/scan.php',
                'skytells\\wp\\skyav\\core' => '/skytells/wp/skyav/core.php',
                'skytells\\wp\\skyav\\cron' => '/skytells/wp/skyav/cron.php',
                'skytells\\wp\\skyav\\db' => '/skytells/wp/skyav/db.php',
                'skytells\\wp\\skyav\\files' => '/skytells/wp/skyav/files.php',
                'skytells\\wp\\skyav\\license' => '/skytells/wp/skyav/license.php',
                'skytells\\wp\\skyav\\options' => '/skytells/wp/skyav/options.php',
                'skytells\\wp\\skyav\\scan' => '/skytells/wp/skyav/scan.php',
                'skytells\\wp\\skyav\\vendor\\common\\bc' => '/vendor/skytells/blob-common/lib/skytells/common/bc.php',
                'skytells\\wp\\skyav\\vendor\\common\\cast' => '/vendor/skytells/blob-common/lib/skytells/common/cast.php',
                'skytells\\wp\\skyav\\vendor\\common\\constants' => '/vendor/skytells/blob-common/lib/skytells/common/constants.php',
                'skytells\\wp\\skyav\\vendor\\common\\data' => '/vendor/skytells/blob-common/lib/skytells/common/data.php',
                'skytells\\wp\\skyav\\vendor\\common\\dom' => '/vendor/skytells/blob-common/lib/skytells/common/dom.php',
                'skytells\\wp\\skyav\\vendor\\common\\file' => '/vendor/skytells/blob-common/lib/skytells/common/file.php',
                'skytells\\wp\\skyav\\vendor\\common\\format' => '/vendor/skytells/blob-common/lib/skytells/common/format.php',
                'skytells\\wp\\skyav\\vendor\\common\\mb' => '/vendor/skytells/blob-common/lib/skytells/common/mb.php',
                'skytells\\wp\\skyav\\vendor\\common\\mime' => '/vendor/skytells/blob-common/lib/skytells/common/mime.php',
                'skytells\\wp\\skyav\\vendor\\common\\ref\\cast' => '/vendor/skytells/blob-common/lib/skytells/common/ref/cast.php',
                'skytells\\wp\\skyav\\vendor\\common\\ref\\cast_base' => '/vendor/skytells/blob-common/lib/skytells/common/ref/cast_base.php',
                'skytells\\wp\\skyav\\vendor\\common\\ref\\cast_full' => '/vendor/skytells/blob-common/lib/skytells/common/ref/cast_full.php',
                'skytells\\wp\\skyav\\vendor\\common\\ref\\file' => '/vendor/skytells/blob-common/lib/skytells/common/ref/file.php',
                'skytells\\wp\\skyav\\vendor\\common\\ref\\format' => '/vendor/skytells/blob-common/lib/skytells/common/ref/format.php',
                'skytells\\wp\\skyav\\vendor\\common\\ref\\mb' => '/vendor/skytells/blob-common/lib/skytells/common/ref/mb.php',
                'skytells\\wp\\skyav\\vendor\\common\\ref\\sanitize' => '/vendor/skytells/blob-common/lib/skytells/common/ref/sanitize.php',
                'skytells\\wp\\skyav\\vendor\\common\\sanitize' => '/vendor/skytells/blob-common/lib/skytells/common/sanitize.php',
                'skytells\\wp\\skyav\\vendor\\domain\\data' => '/vendor/skytells/blob-domain/lib/skytells/domain/data.php',
                'skytells\\wp\\skyav\\vendor\\domain\\domain' => '/vendor/skytells/blob-domain/lib/skytells/domain/domain.php',
                'skytells\\wp\\skyav\\vendor\\mimes\\data' => '/vendor/skytells/blob-mimes/lib/skytells/mimes/data.php',
                'skytells\\wp\\skyav\\vendor\\mimes\\mimes' => '/vendor/skytells/blob-mimes/lib/skytells/mimes/mimes.php'
            );
        }
        if (isset($classes[$class])) {
            require __DIR__ . $classes[$class];
        }
    },
    true,
    false
);
// @codeCoverageIgnoreEnd
